server.port: '${pet.clinic.clinic.server.port:8082}'

eureka:
  instance:
     leaseRenewalInterval: '${pet.clinic.clinic.eureka.instance.leaseRenewalInterval:10}'
     leaseExperationDurationinSecond: '${pet.clinic.clinic.eureka.instance.leaseExperationDurationinSecond:20}'
  client:
    serviceUrl:
      defaultZone: '${pet.clinic.clinic.eureka.client.serviceUrl.defaultZone:http://127.0.0.1:8080/eureka/}'
    healthcheck:
      enabled: '${pet.clinic.clinic.eureka.client.healthCheck.enabled:true}'
    lease:
      duration: '${pet.clinic.clinic.eureka.client.lease.duration:50}'
