spring.profiles.active: production
server.port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petclinic
    username: petclinic_admin
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      format_sql: true
    properties.hibernate.default_schema: local

liquibase:
  change-log: classpath:/liquibase/changelog.xml
  default-schema: local
